app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hide_notification:
    path:     /hide_notifications
    defaults: { _controller: 'AppBundle\Controller\DefaultController::hideNotification' }